// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/json_object.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;
import 'package:myaniapp/graphql/__generated__/media.data.gql.dart'
    show
        GMediaData,
        GMediaData_Media,
        GMediaData_Media_characters,
        GMediaData_Media_characters_nodes,
        GMediaData_Media_coverImage,
        GMediaData_Media_endDate,
        GMediaData_Media_externalLinks,
        GMediaData_Media_mediaListEntry,
        GMediaData_Media_recommendations,
        GMediaData_Media_recommendations_nodes,
        GMediaData_Media_relations,
        GMediaData_Media_relations_edges,
        GMediaData_Media_relations_edges_node,
        GMediaData_Media_relations_edges_node_coverImage,
        GMediaData_Media_relations_edges_node_title,
        GMediaData_Media_reviews,
        GMediaData_Media_reviews_nodes,
        GMediaData_Media_staff,
        GMediaData_Media_staff_nodes,
        GMediaData_Media_startDate,
        GMediaData_Media_studios,
        GMediaData_Media_studios_nodes,
        GMediaData_Media_tags,
        GMediaData_Media_title,
        GMediaData_Media_trailer,
        GToggleFavoriteData,
        GToggleFavoriteData_ToggleFavourite,
        GToggleFavoriteData_ToggleFavourite_anime,
        GToggleFavoriteData_ToggleFavourite_anime_pageInfo,
        GToggleFavoriteData_ToggleFavourite_characters,
        GToggleFavoriteData_ToggleFavourite_characters_pageInfo,
        GToggleFavoriteData_ToggleFavourite_manga,
        GToggleFavoriteData_ToggleFavourite_manga_pageInfo,
        GToggleFavoriteData_ToggleFavourite_staff,
        GToggleFavoriteData_ToggleFavourite_staff_pageInfo,
        GToggleFavoriteData_ToggleFavourite_studios,
        GToggleFavoriteData_ToggleFavourite_studios_pageInfo;
import 'package:myaniapp/graphql/__generated__/media.req.gql.dart'
    show GMediaReq, GToggleFavoriteReq;
import 'package:myaniapp/graphql/__generated__/media.var.gql.dart'
    show GMediaVars, GToggleFavoriteVars;
import 'package:myaniapp/graphql/__generated__/schema.schema.gql.dart'
    show
        GActivitySort,
        GActivityType,
        GAiringScheduleInput,
        GAiringSort,
        GAniChartHighlightInput,
        GCharacterNameInput,
        GCharacterRole,
        GCharacterSort,
        GCountryCode,
        GExternalLinkMediaType,
        GExternalLinkType,
        GFuzzyDateInput,
        GLikeableType,
        GListActivityOptionInput,
        GMediaExternalLinkInput,
        GMediaFormat,
        GMediaListOptionsInput,
        GMediaListSort,
        GMediaListStatus,
        GMediaRankType,
        GMediaRelation,
        GMediaSeason,
        GMediaSort,
        GMediaSource,
        GMediaStatus,
        GMediaTitleInput,
        GMediaTrendSort,
        GMediaType,
        GModActionType,
        GModRole,
        GNotificationOptionInput,
        GNotificationType,
        GRecommendationRating,
        GRecommendationSort,
        GReviewRating,
        GReviewSort,
        GRevisionHistoryAction,
        GScoreFormat,
        GSiteTrendSort,
        GStaffLanguage,
        GStaffNameInput,
        GStaffSort,
        GStudioSort,
        GSubmissionSort,
        GSubmissionStatus,
        GThreadCommentSort,
        GThreadSort,
        GUserSort,
        GUserStaffNameLanguage,
        GUserStatisticsSort,
        GUserTitleLanguage;
import 'package:myaniapp/graphql/__generated__/viewer.data.gql.dart'
    show
        GNotificationCountData,
        GNotificationCountData_Viewer,
        GNotificationCountData_Viewer_options,
        GThisUserData,
        GThisUserData_avatar,
        GThisUserData_mediaListOptions,
        GThisUserData_mediaListOptions_animeList,
        GThisUserData_options,
        GThisUserData_statistics,
        GThisUserData_statistics_anime,
        GThisUserData_statistics_manga,
        GUpdateUserData,
        GUpdateUserData_UpdateUser,
        GUpdateUserData_UpdateUser_avatar,
        GUpdateUserData_UpdateUser_mediaListOptions,
        GUpdateUserData_UpdateUser_mediaListOptions_animeList,
        GUpdateUserData_UpdateUser_options,
        GUpdateUserData_UpdateUser_statistics,
        GUpdateUserData_UpdateUser_statistics_anime,
        GUpdateUserData_UpdateUser_statistics_manga,
        GViewerData,
        GViewerData_Viewer,
        GViewerData_Viewer_avatar,
        GViewerData_Viewer_mediaListOptions,
        GViewerData_Viewer_mediaListOptions_animeList,
        GViewerData_Viewer_options,
        GViewerData_Viewer_statistics,
        GViewerData_Viewer_statistics_anime,
        GViewerData_Viewer_statistics_manga;
import 'package:myaniapp/graphql/__generated__/viewer.req.gql.dart'
    show GNotificationCountReq, GThisUserReq, GUpdateUserReq, GViewerReq;
import 'package:myaniapp/graphql/__generated__/viewer.var.gql.dart'
    show GNotificationCountVars, GThisUserVars, GUpdateUserVars, GViewerVars;
import 'package:myaniapp/graphql/fragments/__generated__/fuzzy_date.data.gql.dart'
    show GFuzzyDateData;
import 'package:myaniapp/graphql/fragments/__generated__/fuzzy_date.req.gql.dart'
    show GFuzzyDateReq;
import 'package:myaniapp/graphql/fragments/__generated__/fuzzy_date.var.gql.dart'
    show GFuzzyDateVars;
import 'package:myaniapp/graphql/fragments/__generated__/list_activity.data.gql.dart'
    show
        GListActivityData,
        GListActivityData_media,
        GListActivityData_media_coverImage,
        GListActivityData_media_title,
        GListActivityData_user,
        GListActivityData_user_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/list_activity.req.gql.dart'
    show GListActivityReq;
import 'package:myaniapp/graphql/fragments/__generated__/list_activity.var.gql.dart'
    show GListActivityVars;
import 'package:myaniapp/graphql/fragments/__generated__/list_group.data.gql.dart'
    show
        GListGroupData,
        GListGroupData_entries,
        GListGroupData_entries_completedAt,
        GListGroupData_entries_media,
        GListGroupData_entries_media_coverImage,
        GListGroupData_entries_media_startDate,
        GListGroupData_entries_media_title,
        GListGroupData_entries_startedAt;
import 'package:myaniapp/graphql/fragments/__generated__/list_group.req.gql.dart'
    show GListGroupReq;
import 'package:myaniapp/graphql/fragments/__generated__/list_group.var.gql.dart'
    show GListGroupVars;
import 'package:myaniapp/graphql/fragments/__generated__/media.data.gql.dart'
    show
        GMediaFragmentData,
        GMediaFragmentData_coverImage,
        GMediaFragmentData_title;
import 'package:myaniapp/graphql/fragments/__generated__/media.req.gql.dart'
    show GMediaFragmentReq;
import 'package:myaniapp/graphql/fragments/__generated__/media.var.gql.dart'
    show GMediaFragmentVars;
import 'package:myaniapp/graphql/fragments/__generated__/media_entry.data.gql.dart'
    show
        GMediaListEntryData,
        GMediaListEntryData_completedAt,
        GMediaListEntryData_media,
        GMediaListEntryData_media_coverImage,
        GMediaListEntryData_media_startDate,
        GMediaListEntryData_media_title,
        GMediaListEntryData_startedAt;
import 'package:myaniapp/graphql/fragments/__generated__/media_entry.req.gql.dart'
    show GMediaListEntryReq;
import 'package:myaniapp/graphql/fragments/__generated__/media_entry.var.gql.dart'
    show GMediaListEntryVars;
import 'package:myaniapp/graphql/fragments/__generated__/media_list_option.data.gql.dart'
    show GMediaListOptionsData;
import 'package:myaniapp/graphql/fragments/__generated__/media_list_option.req.gql.dart'
    show GMediaListOptionsReq;
import 'package:myaniapp/graphql/fragments/__generated__/media_list_option.var.gql.dart'
    show GMediaListOptionsVars;
import 'package:myaniapp/graphql/fragments/__generated__/message_activity.data.gql.dart'
    show
        GMessageActivityData,
        GMessageActivityData_messenger,
        GMessageActivityData_messenger_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/message_activity.req.gql.dart'
    show GMessageActivityReq;
import 'package:myaniapp/graphql/fragments/__generated__/message_activity.var.gql.dart'
    show GMessageActivityVars;
import 'package:myaniapp/graphql/fragments/__generated__/page_info.data.gql.dart'
    show GPageInfoData;
import 'package:myaniapp/graphql/fragments/__generated__/page_info.req.gql.dart'
    show GPageInfoReq;
import 'package:myaniapp/graphql/fragments/__generated__/page_info.var.gql.dart'
    show GPageInfoVars;
import 'package:myaniapp/graphql/fragments/__generated__/releasing_media.data.gql.dart'
    show
        GReleasingMediaData,
        GReleasingMediaData_airingSchedule,
        GReleasingMediaData_airingSchedule_edges,
        GReleasingMediaData_airingSchedule_edges_node,
        GReleasingMediaData_coverImage,
        GReleasingMediaData_nextAiringEpisode,
        GReleasingMediaData_title;
import 'package:myaniapp/graphql/fragments/__generated__/releasing_media.req.gql.dart'
    show GReleasingMediaReq;
import 'package:myaniapp/graphql/fragments/__generated__/releasing_media.var.gql.dart'
    show GReleasingMediaVars;
import 'package:myaniapp/graphql/fragments/__generated__/review.data.gql.dart'
    show
        GReviewData_media,
        GReviewData_media_title,
        GReviewData_user,
        GReviewData_user_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/text_activity.data.gql.dart'
    show
        GTextActivityData,
        GTextActivityData_user,
        GTextActivityData_user_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/text_activity.req.gql.dart'
    show GTextActivityReq;
import 'package:myaniapp/graphql/fragments/__generated__/text_activity.var.gql.dart'
    show GTextActivityVars;
import 'package:myaniapp/graphql/fragments/__generated__/thread.data.gql.dart'
    show
        GThreadFragmentData,
        GThreadFragmentData_categories,
        GThreadFragmentData_mediaCategories,
        GThreadFragmentData_mediaCategories_coverImage,
        GThreadFragmentData_mediaCategories_title,
        GThreadFragmentData_replyUser,
        GThreadFragmentData_replyUser_avatar,
        GThreadFragmentData_user,
        GThreadFragmentData_user_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/thread.req.gql.dart'
    show GThreadFragmentReq;
import 'package:myaniapp/graphql/fragments/__generated__/thread.var.gql.dart'
    show GThreadFragmentVars;
import 'package:myaniapp/graphql/fragments/__generated__/thread_comment.data.gql.dart'
    show GThreadCommentData_user, GThreadCommentData_user_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/user.data.gql.dart'
    show GUserFragmentData, GUserFragmentData_avatar;
import 'package:myaniapp/graphql/fragments/__generated__/user.req.gql.dart'
    show GUserFragmentReq;
import 'package:myaniapp/graphql/fragments/__generated__/user.var.gql.dart'
    show GUserFragmentVars;
import 'package:myaniapp/notifications/__generated__/notifications.data.gql.dart'
    show
        GNotificationsData_Page_notifications,
        GNotificationsData,
        GNotificationsData_Page,
        GNotificationsData_Page_notifications__asActivityLikeNotification,
        GNotificationsData_Page_notifications__asActivityLikeNotification_user,
        GNotificationsData_Page_notifications__asActivityLikeNotification_user_avatar,
        GNotificationsData_Page_notifications__asActivityMentionNotification,
        GNotificationsData_Page_notifications__asActivityMentionNotification_user,
        GNotificationsData_Page_notifications__asActivityMentionNotification_user_avatar,
        GNotificationsData_Page_notifications__asActivityMessageNotification,
        GNotificationsData_Page_notifications__asActivityMessageNotification_user,
        GNotificationsData_Page_notifications__asActivityMessageNotification_user_avatar,
        GNotificationsData_Page_notifications__asActivityReplyLikeNotification,
        GNotificationsData_Page_notifications__asActivityReplyLikeNotification_user,
        GNotificationsData_Page_notifications__asActivityReplyLikeNotification_user_avatar,
        GNotificationsData_Page_notifications__asActivityReplyNotification,
        GNotificationsData_Page_notifications__asActivityReplyNotification_user,
        GNotificationsData_Page_notifications__asActivityReplyNotification_user_avatar,
        GNotificationsData_Page_notifications__asActivityReplySubscribedNotification,
        GNotificationsData_Page_notifications__asActivityReplySubscribedNotification_user,
        GNotificationsData_Page_notifications__asActivityReplySubscribedNotification_user_avatar,
        GNotificationsData_Page_notifications__asAiringNotification,
        GNotificationsData_Page_notifications__asAiringNotification_media,
        GNotificationsData_Page_notifications__asAiringNotification_media_coverImage,
        GNotificationsData_Page_notifications__asAiringNotification_media_title,
        GNotificationsData_Page_notifications__asFollowingNotification,
        GNotificationsData_Page_notifications__asFollowingNotification_user,
        GNotificationsData_Page_notifications__asFollowingNotification_user_avatar,
        GNotificationsData_Page_notifications__asMediaDataChangeNotification,
        GNotificationsData_Page_notifications__asMediaDataChangeNotification_media,
        GNotificationsData_Page_notifications__asMediaDataChangeNotification_media_coverImage,
        GNotificationsData_Page_notifications__asMediaDataChangeNotification_media_title,
        GNotificationsData_Page_notifications__asMediaDeletionNotification,
        GNotificationsData_Page_notifications__asMediaMergeNotification,
        GNotificationsData_Page_notifications__asMediaMergeNotification_media,
        GNotificationsData_Page_notifications__asMediaMergeNotification_media_coverImage,
        GNotificationsData_Page_notifications__asMediaMergeNotification_media_title,
        GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification,
        GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification_media,
        GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification_media_coverImage,
        GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification_media_title,
        GNotificationsData_Page_notifications__asThreadCommentLikeNotification,
        GNotificationsData_Page_notifications__asThreadCommentLikeNotification_thread,
        GNotificationsData_Page_notifications__asThreadCommentLikeNotification_user,
        GNotificationsData_Page_notifications__asThreadCommentLikeNotification_user_avatar,
        GNotificationsData_Page_notifications__asThreadCommentMentionNotification,
        GNotificationsData_Page_notifications__asThreadCommentMentionNotification_thread,
        GNotificationsData_Page_notifications__asThreadCommentMentionNotification_user,
        GNotificationsData_Page_notifications__asThreadCommentMentionNotification_user_avatar,
        GNotificationsData_Page_notifications__asThreadCommentReplyNotification,
        GNotificationsData_Page_notifications__asThreadCommentReplyNotification_thread,
        GNotificationsData_Page_notifications__asThreadCommentReplyNotification_user,
        GNotificationsData_Page_notifications__asThreadCommentReplyNotification_user_avatar,
        GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification,
        GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification_thread,
        GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification_user,
        GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification_user_avatar,
        GNotificationsData_Page_notifications__asThreadLikeNotification,
        GNotificationsData_Page_notifications__asThreadLikeNotification_thread,
        GNotificationsData_Page_notifications__asThreadLikeNotification_user,
        GNotificationsData_Page_notifications__asThreadLikeNotification_user_avatar,
        GNotificationsData_Page_notifications__base,
        GNotificationsData_Page_pageInfo;
import 'package:myaniapp/notifications/__generated__/notifications.req.gql.dart'
    show GNotificationsReq;
import 'package:myaniapp/notifications/__generated__/notifications.var.gql.dart'
    show GNotificationsVars;
import 'package:myaniapp/ui/common/comment/__generated__/like.data.gql.dart'
    show
        GLikesData,
        GLikesData_Page,
        GLikesData_Page_likes,
        GLikesData_Page_likes_avatar,
        GLikesData_Page_pageInfo;
import 'package:myaniapp/ui/common/comment/__generated__/like.req.gql.dart'
    show GLikesReq;
import 'package:myaniapp/ui/common/comment/__generated__/like.var.gql.dart'
    show GLikesVars;
import 'package:myaniapp/ui/common/media_editor/__generated__/media_editor.data.gql.dart'
    show
        GDeleteMediaListEntryData,
        GDeleteMediaListEntryData_DeleteMediaListEntry,
        GMediaEntryData,
        GMediaEntryData_MediaList,
        GMediaEntryData_MediaList_completedAt,
        GMediaEntryData_MediaList_media,
        GMediaEntryData_MediaList_media_coverImage,
        GMediaEntryData_MediaList_media_startDate,
        GMediaEntryData_MediaList_media_title,
        GMediaEntryData_MediaList_startedAt,
        GSaveMediaListEntryData,
        GSaveMediaListEntryData_SaveMediaListEntry,
        GSaveMediaListEntryData_SaveMediaListEntry_completedAt,
        GSaveMediaListEntryData_SaveMediaListEntry_media,
        GSaveMediaListEntryData_SaveMediaListEntry_media_coverImage,
        GSaveMediaListEntryData_SaveMediaListEntry_media_startDate,
        GSaveMediaListEntryData_SaveMediaListEntry_media_title,
        GSaveMediaListEntryData_SaveMediaListEntry_startedAt;
import 'package:myaniapp/ui/common/media_editor/__generated__/media_editor.req.gql.dart'
    show GDeleteMediaListEntryReq, GMediaEntryReq, GSaveMediaListEntryReq;
import 'package:myaniapp/ui/common/media_editor/__generated__/media_editor.var.gql.dart'
    show GDeleteMediaListEntryVars, GMediaEntryVars, GSaveMediaListEntryVars;
import 'package:myaniapp/ui/routes/activity/__generated__/activity.data.gql.dart'
    show
        GActivityData_activity,
        GToggleActivitySubscriptionData_ToggleActivitySubscription,
        GActivityData,
        GActivityData_activity__asListActivity,
        GActivityData_activity__asListActivity_media,
        GActivityData_activity__asListActivity_media_coverImage,
        GActivityData_activity__asListActivity_media_title,
        GActivityData_activity__asListActivity_user,
        GActivityData_activity__asListActivity_user_avatar,
        GActivityData_activity__asMessageActivity,
        GActivityData_activity__asMessageActivity_messenger,
        GActivityData_activity__asMessageActivity_messenger_avatar,
        GActivityData_activity__asTextActivity,
        GActivityData_activity__asTextActivity_user,
        GActivityData_activity__asTextActivity_user_avatar,
        GActivityData_activity__base,
        GActivityData_replies,
        GActivityData_replies_activityReplies,
        GActivityData_replies_activityReplies_user,
        GActivityData_replies_activityReplies_user_avatar,
        GActivityData_replies_pageInfo,
        GDeleteActivityData,
        GDeleteActivityData_DeleteActivity,
        GDeleteActivityReplyData,
        GDeleteActivityReplyData_DeleteActivityReply,
        GSaveActivityReplyData,
        GSaveActivityReplyData_SaveActivityReply,
        GSaveActivityReplyData_SaveActivityReply_user,
        GSaveActivityReplyData_SaveActivityReply_user_avatar,
        GSaveMessageActivityData,
        GSaveMessageActivityData_SaveMessageActivity,
        GSaveMessageActivityData_SaveMessageActivity_messenger,
        GSaveMessageActivityData_SaveMessageActivity_messenger_avatar,
        GToggleActivitySubscriptionData,
        GToggleActivitySubscriptionData_ToggleActivitySubscription__asListActivity,
        GToggleActivitySubscriptionData_ToggleActivitySubscription__asMessageActivity,
        GToggleActivitySubscriptionData_ToggleActivitySubscription__asTextActivity,
        GToggleActivitySubscriptionData_ToggleActivitySubscription__base;
import 'package:myaniapp/ui/routes/activity/__generated__/activity.req.gql.dart'
    show
        GActivityReq,
        GDeleteActivityReplyReq,
        GDeleteActivityReq,
        GSaveActivityReplyReq,
        GSaveMessageActivityReq,
        GToggleActivitySubscriptionReq;
import 'package:myaniapp/ui/routes/activity/__generated__/activity.var.gql.dart'
    show
        GActivityVars,
        GDeleteActivityReplyVars,
        GDeleteActivityVars,
        GSaveActivityReplyVars,
        GSaveMessageActivityVars,
        GToggleActivitySubscriptionVars;
import 'package:myaniapp/ui/routes/calendar/__generated__/calendar.data.gql.dart'
    show
        GCalendarScheduleData,
        GCalendarScheduleData_Page,
        GCalendarScheduleData_Page_airingSchedules,
        GCalendarScheduleData_Page_airingSchedules_media,
        GCalendarScheduleData_Page_airingSchedules_media_coverImage,
        GCalendarScheduleData_Page_airingSchedules_media_title,
        GCalendarScheduleData_Page_pageInfo;
import 'package:myaniapp/ui/routes/calendar/__generated__/calendar.req.gql.dart'
    show GCalendarScheduleReq;
import 'package:myaniapp/ui/routes/calendar/__generated__/calendar.var.gql.dart'
    show GCalendarScheduleVars;
import 'package:myaniapp/ui/routes/calendar/__generated__/listReleases.data.gql.dart'
    show
        GReleasesListData,
        GReleasesListData_Page,
        GReleasesListData_Page_media,
        GReleasesListData_Page_media_airingSchedule,
        GReleasesListData_Page_media_airingSchedule_edges,
        GReleasesListData_Page_media_airingSchedule_edges_node,
        GReleasesListData_Page_media_coverImage,
        GReleasesListData_Page_media_nextAiringEpisode,
        GReleasesListData_Page_media_title,
        GReleasesListData_Page_pageInfo;
import 'package:myaniapp/ui/routes/calendar/__generated__/listReleases.req.gql.dart'
    show GReleasesListReq;
import 'package:myaniapp/ui/routes/calendar/__generated__/listReleases.var.gql.dart'
    show GReleasesListVars;
import 'package:myaniapp/ui/routes/character/__generated__/character.data.gql.dart'
    show
        GCharacterData,
        GCharacterData_Character,
        GCharacterData_Character_dateOfBirth,
        GCharacterData_Character_image,
        GCharacterData_Character_media,
        GCharacterData_Character_media_edges,
        GCharacterData_Character_media_edges_node,
        GCharacterData_Character_media_edges_node_coverImage,
        GCharacterData_Character_media_edges_node_title,
        GCharacterData_Character_media_pageInfo,
        GCharacterData_Character_name;
import 'package:myaniapp/ui/routes/character/__generated__/character.req.gql.dart'
    show GCharacterReq;
import 'package:myaniapp/ui/routes/character/__generated__/character.var.gql.dart'
    show GCharacterVars;
import 'package:myaniapp/ui/routes/explore/__generated__/explore.data.gql.dart'
    show
        GExploreData,
        GExploreData_nextSeason,
        GExploreData_nextSeason_media,
        GExploreData_nextSeason_media_coverImage,
        GExploreData_nextSeason_media_title,
        GExploreData_popular,
        GExploreData_popular_media,
        GExploreData_popular_media_coverImage,
        GExploreData_popular_media_title,
        GExploreData_recent,
        GExploreData_recent_media,
        GExploreData_recent_media_coverImage,
        GExploreData_recent_media_title,
        GExploreData_season,
        GExploreData_season_media,
        GExploreData_season_media_coverImage,
        GExploreData_season_media_title,
        GExploreData_trending,
        GExploreData_trending_media,
        GExploreData_trending_media_coverImage,
        GExploreData_trending_media_title;
import 'package:myaniapp/ui/routes/explore/__generated__/explore.req.gql.dart'
    show GExploreReq;
import 'package:myaniapp/ui/routes/explore/__generated__/explore.var.gql.dart'
    show GExploreVars;
import 'package:myaniapp/ui/routes/forum/__generated__/forums.data.gql.dart'
    show
        GForumsData,
        GForumsData_Page,
        GForumsData_Page_pageInfo,
        GForumsData_Page_threads,
        GForumsData_Page_threads_categories,
        GForumsData_Page_threads_mediaCategories,
        GForumsData_Page_threads_mediaCategories_coverImage,
        GForumsData_Page_threads_mediaCategories_title,
        GForumsData_Page_threads_replyUser,
        GForumsData_Page_threads_replyUser_avatar,
        GForumsData_Page_threads_user,
        GForumsData_Page_threads_user_avatar;
import 'package:myaniapp/ui/routes/forum/__generated__/forums.req.gql.dart'
    show GForumsReq;
import 'package:myaniapp/ui/routes/forum/__generated__/forums.var.gql.dart'
    show GForumsVars;
import 'package:myaniapp/ui/routes/forum/overview/__generated__/overview.data.gql.dart'
    show
        GForumOverviewData,
        GForumOverviewData_new,
        GForumOverviewData_new_threads,
        GForumOverviewData_new_threads_categories,
        GForumOverviewData_new_threads_mediaCategories,
        GForumOverviewData_new_threads_mediaCategories_coverImage,
        GForumOverviewData_new_threads_mediaCategories_title,
        GForumOverviewData_new_threads_replyUser,
        GForumOverviewData_new_threads_replyUser_avatar,
        GForumOverviewData_new_threads_user,
        GForumOverviewData_new_threads_user_avatar,
        GForumOverviewData_recent,
        GForumOverviewData_recent_threads,
        GForumOverviewData_recent_threads_categories,
        GForumOverviewData_recent_threads_mediaCategories,
        GForumOverviewData_recent_threads_mediaCategories_coverImage,
        GForumOverviewData_recent_threads_mediaCategories_title,
        GForumOverviewData_recent_threads_replyUser,
        GForumOverviewData_recent_threads_replyUser_avatar,
        GForumOverviewData_recent_threads_user,
        GForumOverviewData_recent_threads_user_avatar,
        GForumOverviewData_release,
        GForumOverviewData_release_threads,
        GForumOverviewData_release_threads_categories,
        GForumOverviewData_release_threads_mediaCategories,
        GForumOverviewData_release_threads_mediaCategories_coverImage,
        GForumOverviewData_release_threads_mediaCategories_title,
        GForumOverviewData_release_threads_replyUser,
        GForumOverviewData_release_threads_replyUser_avatar,
        GForumOverviewData_release_threads_user,
        GForumOverviewData_release_threads_user_avatar;
import 'package:myaniapp/ui/routes/forum/overview/__generated__/overview.req.gql.dart'
    show GForumOverviewReq;
import 'package:myaniapp/ui/routes/forum/overview/__generated__/overview.var.gql.dart'
    show GForumOverviewVars;
import 'package:myaniapp/ui/routes/home/activities/__generated__/activities.data.gql.dart'
    show
        GActivitiesData_Page_activities,
        GToggleLikeData_ToggleLikeV2,
        GActivitiesData,
        GActivitiesData_Page,
        GActivitiesData_Page_activities__asListActivity,
        GActivitiesData_Page_activities__asListActivity_media,
        GActivitiesData_Page_activities__asListActivity_media_coverImage,
        GActivitiesData_Page_activities__asListActivity_media_title,
        GActivitiesData_Page_activities__asListActivity_user,
        GActivitiesData_Page_activities__asListActivity_user_avatar,
        GActivitiesData_Page_activities__asTextActivity,
        GActivitiesData_Page_activities__asTextActivity_user,
        GActivitiesData_Page_activities__asTextActivity_user_avatar,
        GActivitiesData_Page_activities__base,
        GActivitiesData_Page_pageInfo,
        GSaveTextActivityData,
        GSaveTextActivityData_SaveTextActivity,
        GSaveTextActivityData_SaveTextActivity_user,
        GSaveTextActivityData_SaveTextActivity_user_avatar,
        GToggleLikeData,
        GToggleLikeData_ToggleLikeV2__asActivityReply,
        GToggleLikeData_ToggleLikeV2__asListActivity,
        GToggleLikeData_ToggleLikeV2__asMessageActivity,
        GToggleLikeData_ToggleLikeV2__asTextActivity,
        GToggleLikeData_ToggleLikeV2__asThread,
        GToggleLikeData_ToggleLikeV2__asThreadComment,
        GToggleLikeData_ToggleLikeV2__base;
import 'package:myaniapp/ui/routes/home/activities/__generated__/activities.req.gql.dart'
    show GActivitiesReq, GSaveTextActivityReq, GToggleLikeReq;
import 'package:myaniapp/ui/routes/home/activities/__generated__/activities.var.gql.dart'
    show GActivitiesVars, GSaveTextActivityVars, GToggleLikeVars;
import 'package:myaniapp/ui/routes/home/list/__generated__/list.data.gql.dart'
    show
        GMediaListData,
        GMediaListData_MediaListCollection,
        GMediaListData_MediaListCollection_lists,
        GMediaListData_MediaListCollection_lists_entries,
        GMediaListData_MediaListCollection_lists_entries_completedAt,
        GMediaListData_MediaListCollection_lists_entries_media,
        GMediaListData_MediaListCollection_lists_entries_media_coverImage,
        GMediaListData_MediaListCollection_lists_entries_media_startDate,
        GMediaListData_MediaListCollection_lists_entries_media_title,
        GMediaListData_MediaListCollection_lists_entries_startedAt,
        GMediaListData_MediaListCollection_user,
        GMediaListData_MediaListCollection_user_mediaListOptions,
        GMediaListData_MediaListCollection_user_mediaListOptions_animeList,
        GMediaListData_MediaListCollection_user_mediaListOptions_mangaList;
import 'package:myaniapp/ui/routes/home/list/__generated__/list.req.gql.dart'
    show GMediaListReq;
import 'package:myaniapp/ui/routes/home/list/__generated__/list.var.gql.dart'
    show GMediaListVars;
import 'package:myaniapp/ui/routes/home/overview/__generated__/overview.data.gql.dart'
    show
        GHomeOverviewData,
        GHomeOverviewData_forums,
        GHomeOverviewData_forums_threads,
        GHomeOverviewData_forums_threads_categories,
        GHomeOverviewData_forums_threads_mediaCategories,
        GHomeOverviewData_forums_threads_mediaCategories_coverImage,
        GHomeOverviewData_forums_threads_mediaCategories_title,
        GHomeOverviewData_forums_threads_replyUser,
        GHomeOverviewData_forums_threads_replyUser_avatar,
        GHomeOverviewData_forums_threads_user,
        GHomeOverviewData_forums_threads_user_avatar,
        GHomeOverviewData_list,
        GHomeOverviewData_list_mediaList,
        GHomeOverviewData_list_mediaList_completedAt,
        GHomeOverviewData_list_mediaList_media,
        GHomeOverviewData_list_mediaList_media_coverImage,
        GHomeOverviewData_list_mediaList_media_startDate,
        GHomeOverviewData_list_mediaList_media_title,
        GHomeOverviewData_list_mediaList_startedAt,
        GHomeOverviewData_releasing,
        GHomeOverviewData_releasing_media,
        GHomeOverviewData_releasing_media_airingSchedule,
        GHomeOverviewData_releasing_media_airingSchedule_edges,
        GHomeOverviewData_releasing_media_airingSchedule_edges_node,
        GHomeOverviewData_releasing_media_coverImage,
        GHomeOverviewData_releasing_media_nextAiringEpisode,
        GHomeOverviewData_releasing_media_title,
        GHomeOverviewData_reviews,
        GHomeOverviewData_reviews_reviews,
        GHomeOverviewData_reviews_reviews_media,
        GHomeOverviewData_reviews_reviews_media_title,
        GHomeOverviewData_reviews_reviews_user,
        GHomeOverviewData_reviews_reviews_user_avatar;
import 'package:myaniapp/ui/routes/home/overview/__generated__/overview.req.gql.dart'
    show GHomeOverviewReq;
import 'package:myaniapp/ui/routes/home/overview/__generated__/overview.var.gql.dart'
    show GHomeOverviewVars;
import 'package:myaniapp/ui/routes/media/characters/__generated__/characters.data.gql.dart'
    show
        GCharactersData,
        GCharactersData_Media,
        GCharactersData_Media_characters,
        GCharactersData_Media_characters_edges,
        GCharactersData_Media_characters_edges_node,
        GCharactersData_Media_characters_edges_node_image,
        GCharactersData_Media_characters_edges_node_name,
        GCharactersData_Media_characters_edges_voiceActorRoles,
        GCharactersData_Media_characters_edges_voiceActorRoles_voiceActor,
        GCharactersData_Media_characters_edges_voiceActorRoles_voiceActor_image,
        GCharactersData_Media_characters_edges_voiceActorRoles_voiceActor_name,
        GCharactersData_Media_characters_pageInfo;
import 'package:myaniapp/ui/routes/media/characters/__generated__/characters.req.gql.dart'
    show GCharactersReq;
import 'package:myaniapp/ui/routes/media/characters/__generated__/characters.var.gql.dart'
    show GCharactersVars;
import 'package:myaniapp/ui/routes/media/reviews/__generated__/reviews.data.gql.dart'
    show
        GReviewsData,
        GReviewsData_Media,
        GReviewsData_Media_reviews,
        GReviewsData_Media_reviews_nodes,
        GReviewsData_Media_reviews_nodes_user,
        GReviewsData_Media_reviews_nodes_user_avatar,
        GReviewsData_Media_reviews_pageInfo;
import 'package:myaniapp/ui/routes/media/reviews/__generated__/reviews.req.gql.dart'
    show GReviewsReq;
import 'package:myaniapp/ui/routes/media/reviews/__generated__/reviews.var.gql.dart'
    show GReviewsVars;
import 'package:myaniapp/ui/routes/media/similar/__generated__/similar.data.gql.dart'
    show
        GMediaRecommendationsData,
        GMediaRecommendationsData_Media,
        GMediaRecommendationsData_Media_recommendations,
        GMediaRecommendationsData_Media_recommendations_nodes,
        GMediaRecommendationsData_Media_recommendations_nodes_mediaRecommendation,
        GMediaRecommendationsData_Media_recommendations_nodes_mediaRecommendation_coverImage,
        GMediaRecommendationsData_Media_recommendations_nodes_mediaRecommendation_title,
        GMediaRecommendationsData_Media_recommendations_pageInfo;
import 'package:myaniapp/ui/routes/media/similar/__generated__/similar.req.gql.dart'
    show GMediaRecommendationsReq;
import 'package:myaniapp/ui/routes/media/similar/__generated__/similar.var.gql.dart'
    show GMediaRecommendationsVars;
import 'package:myaniapp/ui/routes/media/social/__generated__/social.data.gql.dart'
    show
        GThreadsData,
        GThreadsData_Page,
        GThreadsData_Page_pageInfo,
        GThreadsData_Page_threads,
        GThreadsData_Page_threads_categories,
        GThreadsData_Page_threads_mediaCategories,
        GThreadsData_Page_threads_mediaCategories_coverImage,
        GThreadsData_Page_threads_mediaCategories_title,
        GThreadsData_Page_threads_replyUser,
        GThreadsData_Page_threads_replyUser_avatar,
        GThreadsData_Page_threads_user,
        GThreadsData_Page_threads_user_avatar;
import 'package:myaniapp/ui/routes/media/social/__generated__/social.req.gql.dart'
    show GThreadsReq;
import 'package:myaniapp/ui/routes/media/social/__generated__/social.var.gql.dart'
    show GThreadsVars;
import 'package:myaniapp/ui/routes/media/staff/__generated__/staff.data.gql.dart'
    show
        GMediaStaffData,
        GMediaStaffData_Media,
        GMediaStaffData_Media_staff,
        GMediaStaffData_Media_staff_edges,
        GMediaStaffData_Media_staff_edges_node,
        GMediaStaffData_Media_staff_edges_node_image,
        GMediaStaffData_Media_staff_edges_node_name,
        GMediaStaffData_Media_staff_pageInfo;
import 'package:myaniapp/ui/routes/media/staff/__generated__/staff.req.gql.dart'
    show GMediaStaffReq;
import 'package:myaniapp/ui/routes/media/staff/__generated__/staff.var.gql.dart'
    show GMediaStaffVars;
import 'package:myaniapp/ui/routes/recommendations/__generated__/recommendations.data.gql.dart'
    show
        GRecommendationsData,
        GRecommendationsData_Page,
        GRecommendationsData_Page_pageInfo,
        GRecommendationsData_Page_recommendations,
        GRecommendationsData_Page_recommendations_media,
        GRecommendationsData_Page_recommendations_mediaRecommendation,
        GRecommendationsData_Page_recommendations_mediaRecommendation_coverImage,
        GRecommendationsData_Page_recommendations_mediaRecommendation_title,
        GRecommendationsData_Page_recommendations_media_coverImage,
        GRecommendationsData_Page_recommendations_media_title,
        GSaveRecommendationData,
        GSaveRecommendationData_SaveRecommendation,
        GSaveRecommendationData_SaveRecommendation_media,
        GSaveRecommendationData_SaveRecommendation_mediaRecommendation,
        GSaveRecommendationData_SaveRecommendation_mediaRecommendation_coverImage,
        GSaveRecommendationData_SaveRecommendation_mediaRecommendation_title,
        GSaveRecommendationData_SaveRecommendation_media_coverImage,
        GSaveRecommendationData_SaveRecommendation_media_title;
import 'package:myaniapp/ui/routes/recommendations/__generated__/recommendations.req.gql.dart'
    show GRecommendationsReq, GSaveRecommendationReq;
import 'package:myaniapp/ui/routes/recommendations/__generated__/recommendations.var.gql.dart'
    show GRecommendationsVars, GSaveRecommendationVars;
import 'package:myaniapp/ui/routes/review/__generated__/review.data.gql.dart'
    show
        GRateReviewData,
        GRateReviewData_RateReview,
        GReviewData,
        GReviewData_Review,
        GReviewData_Review_media,
        GReviewData_Review_media_title,
        GReviewData_Review_user,
        GReviewData_Review_user_avatar;
import 'package:myaniapp/ui/routes/review/__generated__/review.req.gql.dart'
    show GRateReviewReq, GReviewReq;
import 'package:myaniapp/ui/routes/review/__generated__/review.var.gql.dart'
    show GRateReviewVars, GReviewVars;
import 'package:myaniapp/ui/routes/search/__generated__/search.data.gql.dart'
    show
        GGenreCollectionData,
        GGenreCollectionData_tags,
        GSearchData,
        GSearchData_Page,
        GSearchData_Page_media,
        GSearchData_Page_media_coverImage,
        GSearchData_Page_media_title,
        GSearchData_Page_pageInfo;
import 'package:myaniapp/ui/routes/search/__generated__/search.req.gql.dart'
    show GGenreCollectionReq, GSearchReq;
import 'package:myaniapp/ui/routes/search/__generated__/search.var.gql.dart'
    show GGenreCollectionVars, GSearchVars;
import 'package:myaniapp/ui/routes/staff/__generated__/staff.data.gql.dart'
    show
        GStaffData,
        GStaffData_Staff,
        GStaffData_Staff_characterMedia,
        GStaffData_Staff_characterMedia_edges,
        GStaffData_Staff_characterMedia_edges_characters,
        GStaffData_Staff_characterMedia_edges_characters_image,
        GStaffData_Staff_characterMedia_edges_characters_name,
        GStaffData_Staff_characterMedia_edges_node,
        GStaffData_Staff_characterMedia_edges_node_coverImage,
        GStaffData_Staff_characterMedia_edges_node_startDate,
        GStaffData_Staff_characterMedia_edges_node_title,
        GStaffData_Staff_characterMedia_pageInfo,
        GStaffData_Staff_dateOfBirth,
        GStaffData_Staff_dateOfDeath,
        GStaffData_Staff_image,
        GStaffData_Staff_name,
        GStaffData_Staff_staffMedia,
        GStaffData_Staff_staffMedia_edges,
        GStaffData_Staff_staffMedia_edges_node,
        GStaffData_Staff_staffMedia_edges_node_coverImage,
        GStaffData_Staff_staffMedia_edges_node_title,
        GStaffData_Staff_staffMedia_pageInfo;
import 'package:myaniapp/ui/routes/staff/__generated__/staff.req.gql.dart'
    show GStaffReq;
import 'package:myaniapp/ui/routes/staff/__generated__/staff.var.gql.dart'
    show GStaffVars;
import 'package:myaniapp/ui/routes/thread/__generated__/thread.data.gql.dart'
    show
        GDeleteCommentData,
        GDeleteCommentData_DeleteThreadComment,
        GSaveCommentData,
        GSaveCommentData_SaveThreadComment,
        GSaveCommentData_SaveThreadComment_user,
        GSaveCommentData_SaveThreadComment_user_avatar,
        GThreadData,
        GThreadData_comments,
        GThreadData_comments_pageInfo,
        GThreadData_comments_threadComments,
        GThreadData_comments_threadComments_user,
        GThreadData_comments_threadComments_user_avatar,
        GThreadData_thread,
        GThreadData_thread_categories,
        GThreadData_thread_mediaCategories,
        GThreadData_thread_mediaCategories_coverImage,
        GThreadData_thread_mediaCategories_title,
        GThreadData_thread_replyUser,
        GThreadData_thread_replyUser_avatar,
        GThreadData_thread_user,
        GThreadData_thread_user_avatar,
        GToggleThreadSubscriptionData,
        GToggleThreadSubscriptionData_ToggleThreadSubscription;
import 'package:myaniapp/ui/routes/thread/__generated__/thread.req.gql.dart'
    show
        GDeleteCommentReq,
        GSaveCommentReq,
        GThreadReq,
        GToggleThreadSubscriptionReq;
import 'package:myaniapp/ui/routes/thread/__generated__/thread.var.gql.dart'
    show
        GDeleteCommentVars,
        GSaveCommentVars,
        GThreadVars,
        GToggleThreadSubscriptionVars;
import 'package:myaniapp/ui/routes/thread/comment/__generated__/comment.data.gql.dart'
    show
        GThreadCommentData,
        GThreadCommentData_ThreadComment,
        GThreadCommentData_ThreadComment_user,
        GThreadCommentData_ThreadComment_user_avatar;
import 'package:myaniapp/ui/routes/thread/comment/__generated__/comment.req.gql.dart'
    show GThreadCommentReq;
import 'package:myaniapp/ui/routes/thread/comment/__generated__/comment.var.gql.dart'
    show GThreadCommentVars;
import 'package:myaniapp/ui/routes/user/__generated__/user.data.gql.dart'
    show
        GGenreStatData,
        GUserData,
        GUserData_User,
        GUserData_User_avatar,
        GUserData_User_favourites,
        GUserData_User_favourites_anime,
        GUserData_User_favourites_anime_nodes,
        GUserData_User_favourites_anime_nodes_coverImage,
        GUserData_User_favourites_anime_nodes_title,
        GUserData_User_favourites_manga,
        GUserData_User_favourites_manga_nodes,
        GUserData_User_favourites_manga_nodes_coverImage,
        GUserData_User_favourites_manga_nodes_title,
        GUserData_User_mediaListOptions,
        GUserData_User_statistics,
        GUserData_User_statistics_anime,
        GUserData_User_statistics_anime_genres,
        GUserData_User_statistics_manga,
        GUserData_User_statistics_manga_genres;
import 'package:myaniapp/ui/routes/user/__generated__/user.req.gql.dart'
    show GGenreStatReq, GUserReq;
import 'package:myaniapp/ui/routes/user/__generated__/user.var.gql.dart'
    show GGenreStatVars, GUserVars;
import 'package:myaniapp/ui/routes/user/activity/__generated__/activity.data.gql.dart'
    show
        GUserActivitiesData_Page_activities,
        GUserActivitiesData,
        GUserActivitiesData_Page,
        GUserActivitiesData_Page_activities__asListActivity,
        GUserActivitiesData_Page_activities__asListActivity_media,
        GUserActivitiesData_Page_activities__asListActivity_media_coverImage,
        GUserActivitiesData_Page_activities__asListActivity_media_title,
        GUserActivitiesData_Page_activities__asListActivity_user,
        GUserActivitiesData_Page_activities__asListActivity_user_avatar,
        GUserActivitiesData_Page_activities__asMessageActivity,
        GUserActivitiesData_Page_activities__asMessageActivity_messenger,
        GUserActivitiesData_Page_activities__asMessageActivity_messenger_avatar,
        GUserActivitiesData_Page_activities__asTextActivity,
        GUserActivitiesData_Page_activities__asTextActivity_user,
        GUserActivitiesData_Page_activities__asTextActivity_user_avatar,
        GUserActivitiesData_Page_activities__base,
        GUserActivitiesData_Page_pageInfo;
import 'package:myaniapp/ui/routes/user/activity/__generated__/activity.req.gql.dart'
    show GUserActivitiesReq;
import 'package:myaniapp/ui/routes/user/activity/__generated__/activity.var.gql.dart'
    show GUserActivitiesVars;
import 'package:myaniapp/ui/routes/user/reviews/__generated__/reviews.data.gql.dart'
    show
        GUserReviewsData,
        GUserReviewsData_Page,
        GUserReviewsData_Page_pageInfo,
        GUserReviewsData_Page_reviews,
        GUserReviewsData_Page_reviews_media,
        GUserReviewsData_Page_reviews_media_title,
        GUserReviewsData_Page_reviews_user,
        GUserReviewsData_Page_reviews_user_avatar;
import 'package:myaniapp/ui/routes/user/reviews/__generated__/reviews.req.gql.dart'
    show GUserReviewsReq;
import 'package:myaniapp/ui/routes/user/reviews/__generated__/reviews.var.gql.dart'
    show GUserReviewsVars;
import 'package:myaniapp/ui/routes/user/social/__generated__/social.data.gql.dart'
    show
        GSocialsData,
        GSocialsData_followers,
        GSocialsData_followers_followers,
        GSocialsData_followers_followers_avatar,
        GSocialsData_followers_pageInfo,
        GSocialsData_following,
        GSocialsData_following_following,
        GSocialsData_following_following_avatar,
        GSocialsData_following_pageInfo;
import 'package:myaniapp/ui/routes/user/social/__generated__/social.req.gql.dart'
    show GSocialsReq;
import 'package:myaniapp/ui/routes/user/social/__generated__/social.var.gql.dart'
    show GSocialsVars;
import 'package:myaniapp/ui/routes/user/stats/__generated__/stats.data.gql.dart'
    show
        GUserStatsData,
        GUserStatsData_User,
        GUserStatsData_User_statistics,
        GUserStatsData_User_statistics_anime,
        GUserStatsData_User_statistics_anime_countries,
        GUserStatsData_User_statistics_anime_formats,
        GUserStatsData_User_statistics_anime_lengths,
        GUserStatsData_User_statistics_anime_releaseYears,
        GUserStatsData_User_statistics_anime_scores,
        GUserStatsData_User_statistics_anime_startYears,
        GUserStatsData_User_statistics_anime_statuses;
import 'package:myaniapp/ui/routes/user/stats/__generated__/stats.req.gql.dart'
    show GUserStatsReq;
import 'package:myaniapp/ui/routes/user/stats/__generated__/stats.var.gql.dart'
    show GUserStatsVars;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(GActivitiesData_Page_activities.serializer)
  ..add(GActivityData_activity.serializer)
  ..add(GNotificationsData_Page_notifications.serializer)
  ..add(GToggleActivitySubscriptionData_ToggleActivitySubscription.serializer)
  ..add(GToggleLikeData_ToggleLikeV2.serializer)
  ..add(GUserActivitiesData_Page_activities.serializer)
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GActivitiesData,
  GActivitiesData_Page,
  GActivitiesData_Page_activities__asListActivity,
  GActivitiesData_Page_activities__asListActivity_media,
  GActivitiesData_Page_activities__asListActivity_media_coverImage,
  GActivitiesData_Page_activities__asListActivity_media_title,
  GActivitiesData_Page_activities__asListActivity_user,
  GActivitiesData_Page_activities__asListActivity_user_avatar,
  GActivitiesData_Page_activities__asTextActivity,
  GActivitiesData_Page_activities__asTextActivity_user,
  GActivitiesData_Page_activities__asTextActivity_user_avatar,
  GActivitiesData_Page_activities__base,
  GActivitiesData_Page_pageInfo,
  GActivitiesReq,
  GActivitiesVars,
  GActivityData,
  GActivityData_activity__asListActivity,
  GActivityData_activity__asListActivity_media,
  GActivityData_activity__asListActivity_media_coverImage,
  GActivityData_activity__asListActivity_media_title,
  GActivityData_activity__asListActivity_user,
  GActivityData_activity__asListActivity_user_avatar,
  GActivityData_activity__asMessageActivity,
  GActivityData_activity__asMessageActivity_messenger,
  GActivityData_activity__asMessageActivity_messenger_avatar,
  GActivityData_activity__asTextActivity,
  GActivityData_activity__asTextActivity_user,
  GActivityData_activity__asTextActivity_user_avatar,
  GActivityData_activity__base,
  GActivityData_replies,
  GActivityData_replies_activityReplies,
  GActivityData_replies_activityReplies_user,
  GActivityData_replies_activityReplies_user_avatar,
  GActivityData_replies_pageInfo,
  GActivityReq,
  GActivitySort,
  GActivityType,
  GActivityVars,
  GAiringScheduleInput,
  GAiringSort,
  GAniChartHighlightInput,
  GCalendarScheduleData,
  GCalendarScheduleData_Page,
  GCalendarScheduleData_Page_airingSchedules,
  GCalendarScheduleData_Page_airingSchedules_media,
  GCalendarScheduleData_Page_airingSchedules_media_coverImage,
  GCalendarScheduleData_Page_airingSchedules_media_title,
  GCalendarScheduleData_Page_pageInfo,
  GCalendarScheduleReq,
  GCalendarScheduleVars,
  GCharacterData,
  GCharacterData_Character,
  GCharacterData_Character_dateOfBirth,
  GCharacterData_Character_image,
  GCharacterData_Character_media,
  GCharacterData_Character_media_edges,
  GCharacterData_Character_media_edges_node,
  GCharacterData_Character_media_edges_node_coverImage,
  GCharacterData_Character_media_edges_node_title,
  GCharacterData_Character_media_pageInfo,
  GCharacterData_Character_name,
  GCharacterNameInput,
  GCharacterReq,
  GCharacterRole,
  GCharacterSort,
  GCharacterVars,
  GCharactersData,
  GCharactersData_Media,
  GCharactersData_Media_characters,
  GCharactersData_Media_characters_edges,
  GCharactersData_Media_characters_edges_node,
  GCharactersData_Media_characters_edges_node_image,
  GCharactersData_Media_characters_edges_node_name,
  GCharactersData_Media_characters_edges_voiceActorRoles,
  GCharactersData_Media_characters_edges_voiceActorRoles_voiceActor,
  GCharactersData_Media_characters_edges_voiceActorRoles_voiceActor_image,
  GCharactersData_Media_characters_edges_voiceActorRoles_voiceActor_name,
  GCharactersData_Media_characters_pageInfo,
  GCharactersReq,
  GCharactersVars,
  GCountryCode,
  GDeleteActivityData,
  GDeleteActivityData_DeleteActivity,
  GDeleteActivityReplyData,
  GDeleteActivityReplyData_DeleteActivityReply,
  GDeleteActivityReplyReq,
  GDeleteActivityReplyVars,
  GDeleteActivityReq,
  GDeleteActivityVars,
  GDeleteCommentData,
  GDeleteCommentData_DeleteThreadComment,
  GDeleteCommentReq,
  GDeleteCommentVars,
  GDeleteMediaListEntryData,
  GDeleteMediaListEntryData_DeleteMediaListEntry,
  GDeleteMediaListEntryReq,
  GDeleteMediaListEntryVars,
  GExploreData,
  GExploreData_nextSeason,
  GExploreData_nextSeason_media,
  GExploreData_nextSeason_media_coverImage,
  GExploreData_nextSeason_media_title,
  GExploreData_popular,
  GExploreData_popular_media,
  GExploreData_popular_media_coverImage,
  GExploreData_popular_media_title,
  GExploreData_recent,
  GExploreData_recent_media,
  GExploreData_recent_media_coverImage,
  GExploreData_recent_media_title,
  GExploreData_season,
  GExploreData_season_media,
  GExploreData_season_media_coverImage,
  GExploreData_season_media_title,
  GExploreData_trending,
  GExploreData_trending_media,
  GExploreData_trending_media_coverImage,
  GExploreData_trending_media_title,
  GExploreReq,
  GExploreVars,
  GExternalLinkMediaType,
  GExternalLinkType,
  GForumOverviewData,
  GForumOverviewData_new,
  GForumOverviewData_new_threads,
  GForumOverviewData_new_threads_categories,
  GForumOverviewData_new_threads_mediaCategories,
  GForumOverviewData_new_threads_mediaCategories_coverImage,
  GForumOverviewData_new_threads_mediaCategories_title,
  GForumOverviewData_new_threads_replyUser,
  GForumOverviewData_new_threads_replyUser_avatar,
  GForumOverviewData_new_threads_user,
  GForumOverviewData_new_threads_user_avatar,
  GForumOverviewData_recent,
  GForumOverviewData_recent_threads,
  GForumOverviewData_recent_threads_categories,
  GForumOverviewData_recent_threads_mediaCategories,
  GForumOverviewData_recent_threads_mediaCategories_coverImage,
  GForumOverviewData_recent_threads_mediaCategories_title,
  GForumOverviewData_recent_threads_replyUser,
  GForumOverviewData_recent_threads_replyUser_avatar,
  GForumOverviewData_recent_threads_user,
  GForumOverviewData_recent_threads_user_avatar,
  GForumOverviewData_release,
  GForumOverviewData_release_threads,
  GForumOverviewData_release_threads_categories,
  GForumOverviewData_release_threads_mediaCategories,
  GForumOverviewData_release_threads_mediaCategories_coverImage,
  GForumOverviewData_release_threads_mediaCategories_title,
  GForumOverviewData_release_threads_replyUser,
  GForumOverviewData_release_threads_replyUser_avatar,
  GForumOverviewData_release_threads_user,
  GForumOverviewData_release_threads_user_avatar,
  GForumOverviewReq,
  GForumOverviewVars,
  GForumsData,
  GForumsData_Page,
  GForumsData_Page_pageInfo,
  GForumsData_Page_threads,
  GForumsData_Page_threads_categories,
  GForumsData_Page_threads_mediaCategories,
  GForumsData_Page_threads_mediaCategories_coverImage,
  GForumsData_Page_threads_mediaCategories_title,
  GForumsData_Page_threads_replyUser,
  GForumsData_Page_threads_replyUser_avatar,
  GForumsData_Page_threads_user,
  GForumsData_Page_threads_user_avatar,
  GForumsReq,
  GForumsVars,
  GFuzzyDateData,
  GFuzzyDateInput,
  GFuzzyDateReq,
  GFuzzyDateVars,
  GGenreCollectionData,
  GGenreCollectionData_tags,
  GGenreCollectionReq,
  GGenreCollectionVars,
  GGenreStatData,
  GGenreStatReq,
  GGenreStatVars,
  GHomeOverviewData,
  GHomeOverviewData_forums,
  GHomeOverviewData_forums_threads,
  GHomeOverviewData_forums_threads_categories,
  GHomeOverviewData_forums_threads_mediaCategories,
  GHomeOverviewData_forums_threads_mediaCategories_coverImage,
  GHomeOverviewData_forums_threads_mediaCategories_title,
  GHomeOverviewData_forums_threads_replyUser,
  GHomeOverviewData_forums_threads_replyUser_avatar,
  GHomeOverviewData_forums_threads_user,
  GHomeOverviewData_forums_threads_user_avatar,
  GHomeOverviewData_list,
  GHomeOverviewData_list_mediaList,
  GHomeOverviewData_list_mediaList_completedAt,
  GHomeOverviewData_list_mediaList_media,
  GHomeOverviewData_list_mediaList_media_coverImage,
  GHomeOverviewData_list_mediaList_media_startDate,
  GHomeOverviewData_list_mediaList_media_title,
  GHomeOverviewData_list_mediaList_startedAt,
  GHomeOverviewData_releasing,
  GHomeOverviewData_releasing_media,
  GHomeOverviewData_releasing_media_airingSchedule,
  GHomeOverviewData_releasing_media_airingSchedule_edges,
  GHomeOverviewData_releasing_media_airingSchedule_edges_node,
  GHomeOverviewData_releasing_media_coverImage,
  GHomeOverviewData_releasing_media_nextAiringEpisode,
  GHomeOverviewData_releasing_media_title,
  GHomeOverviewData_reviews,
  GHomeOverviewData_reviews_reviews,
  GHomeOverviewData_reviews_reviews_media,
  GHomeOverviewData_reviews_reviews_media_title,
  GHomeOverviewData_reviews_reviews_user,
  GHomeOverviewData_reviews_reviews_user_avatar,
  GHomeOverviewReq,
  GHomeOverviewVars,
  GLikeableType,
  GLikesData,
  GLikesData_Page,
  GLikesData_Page_likes,
  GLikesData_Page_likes_avatar,
  GLikesData_Page_pageInfo,
  GLikesReq,
  GLikesVars,
  GListActivityData,
  GListActivityData_media,
  GListActivityData_media_coverImage,
  GListActivityData_media_title,
  GListActivityData_user,
  GListActivityData_user_avatar,
  GListActivityOptionInput,
  GListActivityReq,
  GListActivityVars,
  GListGroupData,
  GListGroupData_entries,
  GListGroupData_entries_completedAt,
  GListGroupData_entries_media,
  GListGroupData_entries_media_coverImage,
  GListGroupData_entries_media_startDate,
  GListGroupData_entries_media_title,
  GListGroupData_entries_startedAt,
  GListGroupReq,
  GListGroupVars,
  GMediaData,
  GMediaData_Media,
  GMediaData_Media_characters,
  GMediaData_Media_characters_nodes,
  GMediaData_Media_coverImage,
  GMediaData_Media_endDate,
  GMediaData_Media_externalLinks,
  GMediaData_Media_mediaListEntry,
  GMediaData_Media_recommendations,
  GMediaData_Media_recommendations_nodes,
  GMediaData_Media_relations,
  GMediaData_Media_relations_edges,
  GMediaData_Media_relations_edges_node,
  GMediaData_Media_relations_edges_node_coverImage,
  GMediaData_Media_relations_edges_node_title,
  GMediaData_Media_reviews,
  GMediaData_Media_reviews_nodes,
  GMediaData_Media_staff,
  GMediaData_Media_staff_nodes,
  GMediaData_Media_startDate,
  GMediaData_Media_studios,
  GMediaData_Media_studios_nodes,
  GMediaData_Media_tags,
  GMediaData_Media_title,
  GMediaData_Media_trailer,
  GMediaEntryData,
  GMediaEntryData_MediaList,
  GMediaEntryData_MediaList_completedAt,
  GMediaEntryData_MediaList_media,
  GMediaEntryData_MediaList_media_coverImage,
  GMediaEntryData_MediaList_media_startDate,
  GMediaEntryData_MediaList_media_title,
  GMediaEntryData_MediaList_startedAt,
  GMediaEntryReq,
  GMediaEntryVars,
  GMediaExternalLinkInput,
  GMediaFormat,
  GMediaFragmentData,
  GMediaFragmentData_coverImage,
  GMediaFragmentData_title,
  GMediaFragmentReq,
  GMediaFragmentVars,
  GMediaListData,
  GMediaListData_MediaListCollection,
  GMediaListData_MediaListCollection_lists,
  GMediaListData_MediaListCollection_lists_entries,
  GMediaListData_MediaListCollection_lists_entries_completedAt,
  GMediaListData_MediaListCollection_lists_entries_media,
  GMediaListData_MediaListCollection_lists_entries_media_coverImage,
  GMediaListData_MediaListCollection_lists_entries_media_startDate,
  GMediaListData_MediaListCollection_lists_entries_media_title,
  GMediaListData_MediaListCollection_lists_entries_startedAt,
  GMediaListData_MediaListCollection_user,
  GMediaListData_MediaListCollection_user_mediaListOptions,
  GMediaListData_MediaListCollection_user_mediaListOptions_animeList,
  GMediaListData_MediaListCollection_user_mediaListOptions_mangaList,
  GMediaListEntryData,
  GMediaListEntryData_completedAt,
  GMediaListEntryData_media,
  GMediaListEntryData_media_coverImage,
  GMediaListEntryData_media_startDate,
  GMediaListEntryData_media_title,
  GMediaListEntryData_startedAt,
  GMediaListEntryReq,
  GMediaListEntryVars,
  GMediaListOptionsData,
  GMediaListOptionsInput,
  GMediaListOptionsReq,
  GMediaListOptionsVars,
  GMediaListReq,
  GMediaListSort,
  GMediaListStatus,
  GMediaListVars,
  GMediaRankType,
  GMediaRecommendationsData,
  GMediaRecommendationsData_Media,
  GMediaRecommendationsData_Media_recommendations,
  GMediaRecommendationsData_Media_recommendations_nodes,
  GMediaRecommendationsData_Media_recommendations_nodes_mediaRecommendation,
  GMediaRecommendationsData_Media_recommendations_nodes_mediaRecommendation_coverImage,
  GMediaRecommendationsData_Media_recommendations_nodes_mediaRecommendation_title,
  GMediaRecommendationsData_Media_recommendations_pageInfo,
  GMediaRecommendationsReq,
  GMediaRecommendationsVars,
  GMediaRelation,
  GMediaReq,
  GMediaSeason,
  GMediaSort,
  GMediaSource,
  GMediaStaffData,
  GMediaStaffData_Media,
  GMediaStaffData_Media_staff,
  GMediaStaffData_Media_staff_edges,
  GMediaStaffData_Media_staff_edges_node,
  GMediaStaffData_Media_staff_edges_node_image,
  GMediaStaffData_Media_staff_edges_node_name,
  GMediaStaffData_Media_staff_pageInfo,
  GMediaStaffReq,
  GMediaStaffVars,
  GMediaStatus,
  GMediaTitleInput,
  GMediaTrendSort,
  GMediaType,
  GMediaVars,
  GMessageActivityData,
  GMessageActivityData_messenger,
  GMessageActivityData_messenger_avatar,
  GMessageActivityReq,
  GMessageActivityVars,
  GModActionType,
  GModRole,
  GNotificationCountData,
  GNotificationCountData_Viewer,
  GNotificationCountData_Viewer_options,
  GNotificationCountReq,
  GNotificationCountVars,
  GNotificationOptionInput,
  GNotificationType,
  GNotificationsData,
  GNotificationsData_Page,
  GNotificationsData_Page_notifications__asActivityLikeNotification,
  GNotificationsData_Page_notifications__asActivityLikeNotification_user,
  GNotificationsData_Page_notifications__asActivityLikeNotification_user_avatar,
  GNotificationsData_Page_notifications__asActivityMentionNotification,
  GNotificationsData_Page_notifications__asActivityMentionNotification_user,
  GNotificationsData_Page_notifications__asActivityMentionNotification_user_avatar,
  GNotificationsData_Page_notifications__asActivityMessageNotification,
  GNotificationsData_Page_notifications__asActivityMessageNotification_user,
  GNotificationsData_Page_notifications__asActivityMessageNotification_user_avatar,
  GNotificationsData_Page_notifications__asActivityReplyLikeNotification,
  GNotificationsData_Page_notifications__asActivityReplyLikeNotification_user,
  GNotificationsData_Page_notifications__asActivityReplyLikeNotification_user_avatar,
  GNotificationsData_Page_notifications__asActivityReplyNotification,
  GNotificationsData_Page_notifications__asActivityReplyNotification_user,
  GNotificationsData_Page_notifications__asActivityReplyNotification_user_avatar,
  GNotificationsData_Page_notifications__asActivityReplySubscribedNotification,
  GNotificationsData_Page_notifications__asActivityReplySubscribedNotification_user,
  GNotificationsData_Page_notifications__asActivityReplySubscribedNotification_user_avatar,
  GNotificationsData_Page_notifications__asAiringNotification,
  GNotificationsData_Page_notifications__asAiringNotification_media,
  GNotificationsData_Page_notifications__asAiringNotification_media_coverImage,
  GNotificationsData_Page_notifications__asAiringNotification_media_title,
  GNotificationsData_Page_notifications__asFollowingNotification,
  GNotificationsData_Page_notifications__asFollowingNotification_user,
  GNotificationsData_Page_notifications__asFollowingNotification_user_avatar,
  GNotificationsData_Page_notifications__asMediaDataChangeNotification,
  GNotificationsData_Page_notifications__asMediaDataChangeNotification_media,
  GNotificationsData_Page_notifications__asMediaDataChangeNotification_media_coverImage,
  GNotificationsData_Page_notifications__asMediaDataChangeNotification_media_title,
  GNotificationsData_Page_notifications__asMediaDeletionNotification,
  GNotificationsData_Page_notifications__asMediaMergeNotification,
  GNotificationsData_Page_notifications__asMediaMergeNotification_media,
  GNotificationsData_Page_notifications__asMediaMergeNotification_media_coverImage,
  GNotificationsData_Page_notifications__asMediaMergeNotification_media_title,
  GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification,
  GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification_media,
  GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification_media_coverImage,
  GNotificationsData_Page_notifications__asRelatedMediaAdditionNotification_media_title,
  GNotificationsData_Page_notifications__asThreadCommentLikeNotification,
  GNotificationsData_Page_notifications__asThreadCommentLikeNotification_thread,
  GNotificationsData_Page_notifications__asThreadCommentLikeNotification_user,
  GNotificationsData_Page_notifications__asThreadCommentLikeNotification_user_avatar,
  GNotificationsData_Page_notifications__asThreadCommentMentionNotification,
  GNotificationsData_Page_notifications__asThreadCommentMentionNotification_thread,
  GNotificationsData_Page_notifications__asThreadCommentMentionNotification_user,
  GNotificationsData_Page_notifications__asThreadCommentMentionNotification_user_avatar,
  GNotificationsData_Page_notifications__asThreadCommentReplyNotification,
  GNotificationsData_Page_notifications__asThreadCommentReplyNotification_thread,
  GNotificationsData_Page_notifications__asThreadCommentReplyNotification_user,
  GNotificationsData_Page_notifications__asThreadCommentReplyNotification_user_avatar,
  GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification,
  GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification_thread,
  GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification_user,
  GNotificationsData_Page_notifications__asThreadCommentSubscribedNotification_user_avatar,
  GNotificationsData_Page_notifications__asThreadLikeNotification,
  GNotificationsData_Page_notifications__asThreadLikeNotification_thread,
  GNotificationsData_Page_notifications__asThreadLikeNotification_user,
  GNotificationsData_Page_notifications__asThreadLikeNotification_user_avatar,
  GNotificationsData_Page_notifications__base,
  GNotificationsData_Page_pageInfo,
  GNotificationsReq,
  GNotificationsVars,
  GPageInfoData,
  GPageInfoReq,
  GPageInfoVars,
  GRateReviewData,
  GRateReviewData_RateReview,
  GRateReviewReq,
  GRateReviewVars,
  GRecommendationRating,
  GRecommendationSort,
  GRecommendationsData,
  GRecommendationsData_Page,
  GRecommendationsData_Page_pageInfo,
  GRecommendationsData_Page_recommendations,
  GRecommendationsData_Page_recommendations_media,
  GRecommendationsData_Page_recommendations_mediaRecommendation,
  GRecommendationsData_Page_recommendations_mediaRecommendation_coverImage,
  GRecommendationsData_Page_recommendations_mediaRecommendation_title,
  GRecommendationsData_Page_recommendations_media_coverImage,
  GRecommendationsData_Page_recommendations_media_title,
  GRecommendationsReq,
  GRecommendationsVars,
  GReleasesListData,
  GReleasesListData_Page,
  GReleasesListData_Page_media,
  GReleasesListData_Page_media_airingSchedule,
  GReleasesListData_Page_media_airingSchedule_edges,
  GReleasesListData_Page_media_airingSchedule_edges_node,
  GReleasesListData_Page_media_coverImage,
  GReleasesListData_Page_media_nextAiringEpisode,
  GReleasesListData_Page_media_title,
  GReleasesListData_Page_pageInfo,
  GReleasesListReq,
  GReleasesListVars,
  GReleasingMediaData,
  GReleasingMediaData_airingSchedule,
  GReleasingMediaData_airingSchedule_edges,
  GReleasingMediaData_airingSchedule_edges_node,
  GReleasingMediaData_coverImage,
  GReleasingMediaData_nextAiringEpisode,
  GReleasingMediaData_title,
  GReleasingMediaReq,
  GReleasingMediaVars,
  GReviewData,
  GReviewData_Review,
  GReviewData_Review_media,
  GReviewData_Review_media_title,
  GReviewData_Review_user,
  GReviewData_Review_user_avatar,
  GReviewData_media,
  GReviewData_media_title,
  GReviewData_user,
  GReviewData_user_avatar,
  GReviewRating,
  GReviewReq,
  GReviewSort,
  GReviewVars,
  GReviewsData,
  GReviewsData_Media,
  GReviewsData_Media_reviews,
  GReviewsData_Media_reviews_nodes,
  GReviewsData_Media_reviews_nodes_user,
  GReviewsData_Media_reviews_nodes_user_avatar,
  GReviewsData_Media_reviews_pageInfo,
  GReviewsReq,
  GReviewsVars,
  GRevisionHistoryAction,
  GSaveActivityReplyData,
  GSaveActivityReplyData_SaveActivityReply,
  GSaveActivityReplyData_SaveActivityReply_user,
  GSaveActivityReplyData_SaveActivityReply_user_avatar,
  GSaveActivityReplyReq,
  GSaveActivityReplyVars,
  GSaveCommentData,
  GSaveCommentData_SaveThreadComment,
  GSaveCommentData_SaveThreadComment_user,
  GSaveCommentData_SaveThreadComment_user_avatar,
  GSaveCommentReq,
  GSaveCommentVars,
  GSaveMediaListEntryData,
  GSaveMediaListEntryData_SaveMediaListEntry,
  GSaveMediaListEntryData_SaveMediaListEntry_completedAt,
  GSaveMediaListEntryData_SaveMediaListEntry_media,
  GSaveMediaListEntryData_SaveMediaListEntry_media_coverImage,
  GSaveMediaListEntryData_SaveMediaListEntry_media_startDate,
  GSaveMediaListEntryData_SaveMediaListEntry_media_title,
  GSaveMediaListEntryData_SaveMediaListEntry_startedAt,
  GSaveMediaListEntryReq,
  GSaveMediaListEntryVars,
  GSaveMessageActivityData,
  GSaveMessageActivityData_SaveMessageActivity,
  GSaveMessageActivityData_SaveMessageActivity_messenger,
  GSaveMessageActivityData_SaveMessageActivity_messenger_avatar,
  GSaveMessageActivityReq,
  GSaveMessageActivityVars,
  GSaveRecommendationData,
  GSaveRecommendationData_SaveRecommendation,
  GSaveRecommendationData_SaveRecommendation_media,
  GSaveRecommendationData_SaveRecommendation_mediaRecommendation,
  GSaveRecommendationData_SaveRecommendation_mediaRecommendation_coverImage,
  GSaveRecommendationData_SaveRecommendation_mediaRecommendation_title,
  GSaveRecommendationData_SaveRecommendation_media_coverImage,
  GSaveRecommendationData_SaveRecommendation_media_title,
  GSaveRecommendationReq,
  GSaveRecommendationVars,
  GSaveTextActivityData,
  GSaveTextActivityData_SaveTextActivity,
  GSaveTextActivityData_SaveTextActivity_user,
  GSaveTextActivityData_SaveTextActivity_user_avatar,
  GSaveTextActivityReq,
  GSaveTextActivityVars,
  GScoreFormat,
  GSearchData,
  GSearchData_Page,
  GSearchData_Page_media,
  GSearchData_Page_media_coverImage,
  GSearchData_Page_media_title,
  GSearchData_Page_pageInfo,
  GSearchReq,
  GSearchVars,
  GSiteTrendSort,
  GSocialsData,
  GSocialsData_followers,
  GSocialsData_followers_followers,
  GSocialsData_followers_followers_avatar,
  GSocialsData_followers_pageInfo,
  GSocialsData_following,
  GSocialsData_following_following,
  GSocialsData_following_following_avatar,
  GSocialsData_following_pageInfo,
  GSocialsReq,
  GSocialsVars,
  GStaffData,
  GStaffData_Staff,
  GStaffData_Staff_characterMedia,
  GStaffData_Staff_characterMedia_edges,
  GStaffData_Staff_characterMedia_edges_characters,
  GStaffData_Staff_characterMedia_edges_characters_image,
  GStaffData_Staff_characterMedia_edges_characters_name,
  GStaffData_Staff_characterMedia_edges_node,
  GStaffData_Staff_characterMedia_edges_node_coverImage,
  GStaffData_Staff_characterMedia_edges_node_startDate,
  GStaffData_Staff_characterMedia_edges_node_title,
  GStaffData_Staff_characterMedia_pageInfo,
  GStaffData_Staff_dateOfBirth,
  GStaffData_Staff_dateOfDeath,
  GStaffData_Staff_image,
  GStaffData_Staff_name,
  GStaffData_Staff_staffMedia,
  GStaffData_Staff_staffMedia_edges,
  GStaffData_Staff_staffMedia_edges_node,
  GStaffData_Staff_staffMedia_edges_node_coverImage,
  GStaffData_Staff_staffMedia_edges_node_title,
  GStaffData_Staff_staffMedia_pageInfo,
  GStaffLanguage,
  GStaffNameInput,
  GStaffReq,
  GStaffSort,
  GStaffVars,
  GStudioSort,
  GSubmissionSort,
  GSubmissionStatus,
  GTextActivityData,
  GTextActivityData_user,
  GTextActivityData_user_avatar,
  GTextActivityReq,
  GTextActivityVars,
  GThisUserData,
  GThisUserData_avatar,
  GThisUserData_mediaListOptions,
  GThisUserData_mediaListOptions_animeList,
  GThisUserData_options,
  GThisUserData_statistics,
  GThisUserData_statistics_anime,
  GThisUserData_statistics_manga,
  GThisUserReq,
  GThisUserVars,
  GThreadCommentData,
  GThreadCommentData_ThreadComment,
  GThreadCommentData_ThreadComment_user,
  GThreadCommentData_ThreadComment_user_avatar,
  GThreadCommentData_user,
  GThreadCommentData_user_avatar,
  GThreadCommentReq,
  GThreadCommentSort,
  GThreadCommentVars,
  GThreadData,
  GThreadData_comments,
  GThreadData_comments_pageInfo,
  GThreadData_comments_threadComments,
  GThreadData_comments_threadComments_user,
  GThreadData_comments_threadComments_user_avatar,
  GThreadData_thread,
  GThreadData_thread_categories,
  GThreadData_thread_mediaCategories,
  GThreadData_thread_mediaCategories_coverImage,
  GThreadData_thread_mediaCategories_title,
  GThreadData_thread_replyUser,
  GThreadData_thread_replyUser_avatar,
  GThreadData_thread_user,
  GThreadData_thread_user_avatar,
  GThreadFragmentData,
  GThreadFragmentData_categories,
  GThreadFragmentData_mediaCategories,
  GThreadFragmentData_mediaCategories_coverImage,
  GThreadFragmentData_mediaCategories_title,
  GThreadFragmentData_replyUser,
  GThreadFragmentData_replyUser_avatar,
  GThreadFragmentData_user,
  GThreadFragmentData_user_avatar,
  GThreadFragmentReq,
  GThreadFragmentVars,
  GThreadReq,
  GThreadSort,
  GThreadVars,
  GThreadsData,
  GThreadsData_Page,
  GThreadsData_Page_pageInfo,
  GThreadsData_Page_threads,
  GThreadsData_Page_threads_categories,
  GThreadsData_Page_threads_mediaCategories,
  GThreadsData_Page_threads_mediaCategories_coverImage,
  GThreadsData_Page_threads_mediaCategories_title,
  GThreadsData_Page_threads_replyUser,
  GThreadsData_Page_threads_replyUser_avatar,
  GThreadsData_Page_threads_user,
  GThreadsData_Page_threads_user_avatar,
  GThreadsReq,
  GThreadsVars,
  GToggleActivitySubscriptionData,
  GToggleActivitySubscriptionData_ToggleActivitySubscription__asListActivity,
  GToggleActivitySubscriptionData_ToggleActivitySubscription__asMessageActivity,
  GToggleActivitySubscriptionData_ToggleActivitySubscription__asTextActivity,
  GToggleActivitySubscriptionData_ToggleActivitySubscription__base,
  GToggleActivitySubscriptionReq,
  GToggleActivitySubscriptionVars,
  GToggleFavoriteData,
  GToggleFavoriteData_ToggleFavourite,
  GToggleFavoriteData_ToggleFavourite_anime,
  GToggleFavoriteData_ToggleFavourite_anime_pageInfo,
  GToggleFavoriteData_ToggleFavourite_characters,
  GToggleFavoriteData_ToggleFavourite_characters_pageInfo,
  GToggleFavoriteData_ToggleFavourite_manga,
  GToggleFavoriteData_ToggleFavourite_manga_pageInfo,
  GToggleFavoriteData_ToggleFavourite_staff,
  GToggleFavoriteData_ToggleFavourite_staff_pageInfo,
  GToggleFavoriteData_ToggleFavourite_studios,
  GToggleFavoriteData_ToggleFavourite_studios_pageInfo,
  GToggleFavoriteReq,
  GToggleFavoriteVars,
  GToggleLikeData,
  GToggleLikeData_ToggleLikeV2__asActivityReply,
  GToggleLikeData_ToggleLikeV2__asListActivity,
  GToggleLikeData_ToggleLikeV2__asMessageActivity,
  GToggleLikeData_ToggleLikeV2__asTextActivity,
  GToggleLikeData_ToggleLikeV2__asThread,
  GToggleLikeData_ToggleLikeV2__asThreadComment,
  GToggleLikeData_ToggleLikeV2__base,
  GToggleLikeReq,
  GToggleLikeVars,
  GToggleThreadSubscriptionData,
  GToggleThreadSubscriptionData_ToggleThreadSubscription,
  GToggleThreadSubscriptionReq,
  GToggleThreadSubscriptionVars,
  GUpdateUserData,
  GUpdateUserData_UpdateUser,
  GUpdateUserData_UpdateUser_avatar,
  GUpdateUserData_UpdateUser_mediaListOptions,
  GUpdateUserData_UpdateUser_mediaListOptions_animeList,
  GUpdateUserData_UpdateUser_options,
  GUpdateUserData_UpdateUser_statistics,
  GUpdateUserData_UpdateUser_statistics_anime,
  GUpdateUserData_UpdateUser_statistics_manga,
  GUpdateUserReq,
  GUpdateUserVars,
  GUserActivitiesData,
  GUserActivitiesData_Page,
  GUserActivitiesData_Page_activities__asListActivity,
  GUserActivitiesData_Page_activities__asListActivity_media,
  GUserActivitiesData_Page_activities__asListActivity_media_coverImage,
  GUserActivitiesData_Page_activities__asListActivity_media_title,
  GUserActivitiesData_Page_activities__asListActivity_user,
  GUserActivitiesData_Page_activities__asListActivity_user_avatar,
  GUserActivitiesData_Page_activities__asMessageActivity,
  GUserActivitiesData_Page_activities__asMessageActivity_messenger,
  GUserActivitiesData_Page_activities__asMessageActivity_messenger_avatar,
  GUserActivitiesData_Page_activities__asTextActivity,
  GUserActivitiesData_Page_activities__asTextActivity_user,
  GUserActivitiesData_Page_activities__asTextActivity_user_avatar,
  GUserActivitiesData_Page_activities__base,
  GUserActivitiesData_Page_pageInfo,
  GUserActivitiesReq,
  GUserActivitiesVars,
  GUserData,
  GUserData_User,
  GUserData_User_avatar,
  GUserData_User_favourites,
  GUserData_User_favourites_anime,
  GUserData_User_favourites_anime_nodes,
  GUserData_User_favourites_anime_nodes_coverImage,
  GUserData_User_favourites_anime_nodes_title,
  GUserData_User_favourites_manga,
  GUserData_User_favourites_manga_nodes,
  GUserData_User_favourites_manga_nodes_coverImage,
  GUserData_User_favourites_manga_nodes_title,
  GUserData_User_mediaListOptions,
  GUserData_User_statistics,
  GUserData_User_statistics_anime,
  GUserData_User_statistics_anime_genres,
  GUserData_User_statistics_manga,
  GUserData_User_statistics_manga_genres,
  GUserFragmentData,
  GUserFragmentData_avatar,
  GUserFragmentReq,
  GUserFragmentVars,
  GUserReq,
  GUserReviewsData,
  GUserReviewsData_Page,
  GUserReviewsData_Page_pageInfo,
  GUserReviewsData_Page_reviews,
  GUserReviewsData_Page_reviews_media,
  GUserReviewsData_Page_reviews_media_title,
  GUserReviewsData_Page_reviews_user,
  GUserReviewsData_Page_reviews_user_avatar,
  GUserReviewsReq,
  GUserReviewsVars,
  GUserSort,
  GUserStaffNameLanguage,
  GUserStatisticsSort,
  GUserStatsData,
  GUserStatsData_User,
  GUserStatsData_User_statistics,
  GUserStatsData_User_statistics_anime,
  GUserStatsData_User_statistics_anime_countries,
  GUserStatsData_User_statistics_anime_formats,
  GUserStatsData_User_statistics_anime_lengths,
  GUserStatsData_User_statistics_anime_releaseYears,
  GUserStatsData_User_statistics_anime_scores,
  GUserStatsData_User_statistics_anime_startYears,
  GUserStatsData_User_statistics_anime_statuses,
  GUserStatsReq,
  GUserStatsVars,
  GUserTitleLanguage,
  GUserVars,
  GViewerData,
  GViewerData_Viewer,
  GViewerData_Viewer_avatar,
  GViewerData_Viewer_mediaListOptions,
  GViewerData_Viewer_mediaListOptions_animeList,
  GViewerData_Viewer_options,
  GViewerData_Viewer_statistics,
  GViewerData_Viewer_statistics_anime,
  GViewerData_Viewer_statistics_manga,
  GViewerReq,
  GViewerVars,
])
final Serializers serializers = _serializersBuilder.build();
